---

- name: Create nomad group
  group: name=nomad state=present
  become: yes

- name: Create nomad user
  user: group=nomad name=nomad shell=/usr/sbin/nologin state=present
  become: yes

- name: Download nomad
  get_url: dest=/tmp url=https://releases.hashicorp.com/nomad/0.7.0/nomad_0.7.0_linux_amd64.zip validate_certs=no
  register: response
  become: yes

- name: Move nomad binary to PATH
  unarchive: dest=/usr/local/bin mode=+x remote_src=yes src={{ response.dest }}
  when: response.dest is defined
  become: yes

- name: Create nomad configuration and data directories
  file: group=nomad owner=nomad path={{ item }} recurse=yes state=directory
  with_items:
  - /etc/nomad.d
  - /var/lib/nomad/data
  become: yes

- name: Copy nomad unit configuration file
  copy: dest=/lib/systemd/system/nomad.service src=nomad.service
  become: yes
